env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules: {
  quotes: ['error', 'double'], # double quotes are used or else error is shown
  'react/react-in-jsx-scope': 'off', # allows to use jsx without importing React
  "@typescript-eslint/ban-types": "warn" # warns when using not allowed types or incorrect syntax
  }
